import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import mysql.connector
from datetime import datetime, timedelta

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="IBM Quantum Qubit Viability",
    page_icon=None,
    layout="wide",
)

# ── Database connection with real error messages ──────────────────────────────
@st.cache_resource
def get_db_connection():
    try:
        conn = mysql.connector.connect(
            host=st.secrets["MYSQL_HOST"],
            port=int(st.secrets["MYSQL_PORT"]),
            user=st.secrets["MYSQL_USER"],
            password=st.secrets["MYSQL_PASSWORD"],
            database=st.secrets["MYSQL_DATABASE"],
            connection_timeout=10
        )
        return conn
    except KeyError as e:
        st.error(f"Missing secret: {e}. Go to Streamlit Cloud → Settings → Secrets and add all 5 keys.")
        st.stop()
    except mysql.connector.Error as err:
        st.error(f"MySQL Connection Error {err.errno}: {err.msg}")
        if err.errno == 2003:
            st.info("Check MYSQL_HOST and MYSQL_PORT in Secrets. Must match Railway Public Host.")
        elif err.errno == 1045:
            st.info("Access denied. Check MYSQL_USER and MYSQL_PASSWORD in Secrets.")
        elif err.errno == 1049:
            st.info("Database not found. Check MYSQL_DATABASE in Secrets. Should be 'railway'.")
        st.stop()

@st.cache_data(ttl=300)
def get_latest_rankings(backend=None):
    conn = get_db_connection()
    query = """
        SELECT r.backend, r.qubit, r.viability_rank, r.viability_score, r.label, r.snapshot_date,
               c.t1_us, c.t2_us, c.readout_error
        FROM qubit_rankings r
        JOIN qubit_calibration c ON r.backend = c.backend 
            AND r.qubit = c.qubit 
            AND r.snapshot_date = c.snapshot_date
        WHERE r.snapshot_date = (SELECT MAX(snapshot_date) FROM qubit_rankings)
    """
    params = []
    if backend:
        query += " AND r.backend = %s"
        params.append(backend)
    query += " ORDER BY r.backend, r.viability_rank"
    df = pd.read_sql(query, conn, params=params if params else None)
    conn.close()
    return df

@st.cache_data(ttl=300)
def get_ranking_history(backend, qubit, days=7):
    conn = get_db_connection()
    query = """
        SELECT r.snapshot_date, r.viability_score, r.label, 
               c.t1_us, c.t2_us, c.readout_error
        FROM qubit_rankings r
        JOIN qubit_calibration c ON r.backend = c.backend 
            AND r.qubit = c.qubit 
            AND r.snapshot_date = c.snapshot_date
        WHERE r.backend = %s AND r.qubit = %s
            AND r.snapshot_date >= DATE_SUB(CURDATE(), INTERVAL %s DAY)
        ORDER BY r.snapshot_date
    """
    df = pd.read_sql(query, conn, params=(backend, qubit, days))
    conn.close()
    return df

@st.cache_data(ttl=300)
def get_summary_stats():
    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)
    cursor.execute("SELECT COUNT(DISTINCT snapshot_date) as days_collected FROM qubit_rankings")
    days = cursor.fetchone()['days_collected']
    cursor.execute("SELECT MAX(snapshot_date) as latest_date FROM qubit_rankings")
    latest = cursor.fetchone()['latest_date']
    cursor.execute("SELECT COUNT(*) as qubits_latest FROM qubit_rankings WHERE snapshot_date = %s", (latest,))
    qubits = cursor.fetchone()['qubits_latest']
    conn.close()
    return {'days_collected': days, 'latest_date': latest, 'qubits_latest': qubits}

@st.cache_data(ttl=300)
def get_all_backends():
    conn = get_db_connection()
    df = pd.read_sql("SELECT DISTINCT backend FROM qubit_rankings ORDER BY backend", conn)
    conn.close()
    return df['backend'].tolist()

# ── Header ────────────────────────────────────────────────────────────────────
st.title("IBM Quantum — Qubit Viability Live Dashboard")
st.caption(
    "Predictions generated by a Random Forest model (LOBO AUC 0.904) trained on "
    "Dec 28–Jan 02 IBM Heron calibration data. Scores use historical T1/T2/RE features only — "
    "no current-session leakage."
)

# ── Summary stats ─────────────────────────────────────────────────────────────
try:
    stats = get_summary_stats()
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Days Collected", stats['days_collected'])
    col2.metric("Qubits Ranked Today", stats['qubits_latest'])
    col3.metric("Latest Snapshot", str(stats['latest_date']))
    col4.metric("Model", "Random Forest v2")
except Exception as e:
    st.error(f"Failed to load summary stats: {e}")
    st.stop()

st.divider()

# ── Load dynamic backends from DB ─────────────────────────────────────────────
try:
    BACKENDS = get_all_backends()
    if not BACKENDS:
        st.warning("No rankings in database yet. Run collector.py at least once.")
        st.stop()
except Exception as e:
    st.error(f"Failed to load backends: {e}")
    st.stop()

# ── Sidebar controls ──────────────────────────────────────────────────────────
st.sidebar.header("Filters")
selected_backend = st.sidebar.selectbox("Backend", ["All"] + BACKENDS, index=0)
top_n = st.sidebar.slider("Show top N qubits", min_value=5, max_value=50, value=20)
show_only_viable = st.sidebar.checkbox("Show only viable qubits", value=False)

# ── Load rankings ─────────────────────────────────────────────────────────────
backend_filter = None if selected_backend == "All" else selected_backend
df = get_latest_rankings(backend=backend_filter)

if df.empty:
    st.warning("No rankings in database yet. Run collector.py at least once.")
    st.stop()

if show_only_viable:
    df = df[df['label'] == 1]

# ── Tab layout ────────────────────────────────────────────────────────────────
tab1, tab2, tab3 = st.tabs(["Rankings", "Trends", "Backend Comparison"])

# ════════════════════════════════════════════════════════════════════════════
# TAB 1 — Rankings Table
# ════════════════════════════════════════════════════════════════════════════
with tab1:
    st.subheader(f"Top {top_n} Qubits by Viability Score")

    for backend in (BACKENDS if selected_backend == "All" else [selected_backend]):
        sub = df[df['backend'] == backend].nsmallest(top_n, 'viability_rank').copy()
        if sub.empty:
            continue

        st.markdown(f"**{backend}**")

        display = sub[['viability_rank', 'qubit', 'viability_score',
                        't1_us', 't2_us', 'readout_error', 'label']].copy()
        display.columns = ['Rank', 'Qubit', 'Score', 'T1 (μs)', 'T2 (μs)', 'RE', 'Viable']
        display['Viable'] = display['Viable'].map({1: 'Yes', 0: 'No'})
        display['Score'] = display['Score'].round(4)
        display['T1 (μs)'] = display['T1 (μs)'].round(1)
        display['T2 (μs)'] = display['T2 (μs)'].round(1)
        display['RE'] = display['RE'].round(4)

        st.dataframe(
            display.style.apply(
                lambda row: ['background-color: #e8f5e9' if row['Viable'] == 'Yes'
                             else 'background-color: #ffebee'] * len(row),
                axis=1
            ),
            use_container_width=True,
            height=min(400, 40 + 35 * len(display))
        )

# ════════════════════════════════════════════
# TAB 2 — Trend for a specific qubit
# ════════════════════════════════════════════════════════════════════════════
with tab2:
    st.subheader("Viability Score Trend — Single Qubit")

    col_a, col_b = st.columns(2)
    with col_a:
        trend_backend = st.selectbox("Backend", BACKENDS, key="trend_backend")
    with col_b:
        qubit_options = sorted(df[df['backend'] == trend_backend]['qubit'].unique())
        trend_qubit = st.selectbox("Qubit", qubit_options, key="trend_qubit")

    trend_df = get_ranking_history(trend_backend, trend_qubit, days=7)

    if trend_df.empty or len(trend_df) < 2:
        st.info("Need at least 2 days of data to show a trend. Check back tomorrow.")
    else:
        fig, axes = plt.subplots(2, 2, figsize=(12, 8))
        fig.suptitle(f"{trend_backend} — Qubit {trend_qubit} History (7 Days)", fontsize=14)

        dates = pd.to_datetime(trend_df['snapshot_date'])

        axes[0,0].plot(dates, trend_df['viability_score'], marker='o', lw=2)
        axes[0,0].set_title('Viability Score')
        axes[0,0].set_ylim(0, 1)
        axes[0,0].grid(True, alpha=0.3)

        axes[0,1].plot(dates, trend_df['t1_us'], marker='o', lw=2)
        axes[0,1].axhline(100, color='red', ls='--', lw=1, alpha=0.6, label='Threshold')
        axes[0,1].set_title('T1 (μs)')
        axes[0,1].legend(fontsize=8)
        axes[0,1].grid(True, alpha=0.3)

        axes[1,0].plot(dates, trend_df['t2_us'], marker='o', lw=2)
        axes[1,0].axhline(50, color='red', ls='--', lw=1, alpha=0.6, label='Threshold')
        axes[1,0].set_title('T2 (μs)')
        axes[1,0].legend(fontsize=8)
        axes[1,0].grid(True, alpha=0.3)

        axes[1,1].plot(dates, trend_df['readout_error'], marker='o', lw=2)
        axes[1,1].axhline(0.05, color='red', ls='--', lw=1, alpha=0.6, label='Threshold')
        axes[1,1].set_title('Readout Error')
        axes[1,1].legend(fontsize=8)
        axes[1,1].grid(True, alpha=0.3)

        for ax in axes.flat:
            ax.tick_params(axis='x', rotation=30, labelsize=8)

        plt.tight_layout()
        st.pyplot(fig)

# ════════════════════════════════════════════════════════════════════════════
# TAB 3 — Backend Comparison with Large Trend Chart
# ════════════════════════════════════════════════════════════════════════════
with tab3:
    st.subheader("Backend Comparison — Latest Snapshot")

    all_df = get_latest_rankings()
    summary_rows = []
    for b in BACKENDS:
        sub = all_df[all_df['backend'] == b]
        if sub.empty:
            continue
        summary_rows.append({
            'Backend': b,
            'Qubits Ranked': len(sub),
            'Viable (%)': f"{100*sub['label'].mean():.1f}",
            'Mean Score': f"{sub['viability_score'].mean():.3f}",
            'Top Qubit': int(sub.loc[sub['viability_rank'].idxmin(), 'qubit']),
            'Top Score': f"{sub['viability_score'].max():.3f}",
            'Mean T1 (μs)': f"{sub['t1_us'].mean():.1f}",
            'Mean RE': f"{sub['readout_error'].mean():.4f}",
        })
    st.dataframe(pd.DataFrame(summary_rows).set_index('Backend'), use_container_width=True)

    st.subheader("Score Distribution per Backend (Latest Snapshot)")
    fig, ax = plt.subplots(figsize=(12, 5))
    for b in BACKENDS:
        sub = all_df[all_df['backend'] == b]
        if sub.empty: continue
        ax.hist(sub['viability_score'], bins=30, alpha=0.6, label=b)
    ax.set_xlabel('Viability Score')
    ax.set_ylabel('Qubit Count')
    ax.legend()
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    st.pyplot(fig)

    st.subheader("7-Day Viability Trend — Backend Average")
    conn = get_db_connection()
    trend_query = """
        SELECT backend, snapshot_date, AVG(viability_score) as mean_score
        FROM qubit_rankings
        WHERE snapshot_date >= DATE_SUB(CURDATE(), INTERVAL 7 DAY)
        GROUP BY backend, snapshot_date
        ORDER BY snapshot_date
    """
    trend_df = pd.read_sql(trend_query, conn)
    conn.close()

    if not trend_df.empty:
        fig, ax = plt.subplots(figsize=(12, 5))
        for b in BACKENDS:
            sub = trend_df[trend_df['backend'] == b]
            if sub.empty: continue
            ax.plot(pd.to_datetime(sub['snapshot_date']), sub['mean_score'], 
                    marker='o', lw=2, label=b)
        ax.set_xlabel('Date')
        ax.set_ylabel('Mean Viability Score')
        ax.set_ylim(0, 1)
        ax.legend()
        ax.grid(True, alpha=0.3)
        plt.xticks(rotation=30)
        plt.tight_layout()
        st.pyplot(fig)
    else:
        st.info("Need at least 2 days of data to show backend trends.")

# ── Footer ────────────────────────────────────────────────────────────────────
st.divider()
st.caption(
   
    "Author: Vattikuti Uday Kiran"
)