"""
dashboard.py — IBM Quantum Qubit Viability Live Dashboard
Deploy to Streamlit Community Cloud (free, public URL).

Shows:
  - Live qubit rankings per backend
  - Viability score trends over 7 days
  - Top/bottom qubits with full calibration values
  - Backend comparison summary
"""

import os
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from datetime import date
from dotenv import load_dotenv

load_dotenv()

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="IBM Quantum Qubit Viability",
    page_icon="⚛️",
    layout="wide",
)

BACKEND_COLORS = {
    'ibm_fez':       '#5271C4',
    'ibm_torino':    '#E07B39',
    'ibm_marrakesh': '#3BAD6E',
}
BACKENDS = ['ibm_fez', 'ibm_torino', 'ibm_marrakesh']


# ── DB import with error handling ─────────────────────────────────────────────
@st.cache_resource
def load_db():
    try:
        from database import (
            get_latest_rankings, get_ranking_history,
            get_summary_stats, get_all_dates
        )
        return get_latest_rankings, get_ranking_history, get_summary_stats, get_all_dates
    except Exception as e:
        st.error(f"Database connection failed: {e}")
        st.stop()


get_latest_rankings, get_ranking_history, get_summary_stats, get_all_dates = load_db()


# ── Header ────────────────────────────────────────────────────────────────────
st.title("⚛️ IBM Quantum — Qubit Viability Live Dashboard")
st.caption(
    "Predictions generated by a Random Forest model (LOBO AUC 0.904) trained on "
    "Dec 28–Jan 02 IBM Heron calibration data. Scores use historical T1/T2/RE features only — "
    "no current-session leakage."
)

# ── Summary stats ─────────────────────────────────────────────────────────────
try:
    stats = get_summary_stats()
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Days Collected", stats['days_collected'])
    col2.metric("Qubits Ranked Today", stats['qubits_latest'])
    col3.metric("Latest Snapshot", str(stats['latest_date']))
    col4.metric("Model", "Random Forest v2")
except Exception as e:
    st.warning(f"Could not load summary stats: {e}")

st.divider()

# ── Sidebar controls ──────────────────────────────────────────────────────────
st.sidebar.header("Filters")
selected_backend = st.sidebar.selectbox(
    "Backend", ["All"] + BACKENDS, index=0
)
top_n = st.sidebar.slider("Show top N qubits", min_value=5, max_value=50, value=20)
show_only_viable = st.sidebar.checkbox("Show only viable qubits (label=1)", value=False)

# ── Load rankings ─────────────────────────────────────────────────────────────
try:
    backend_filter = None if selected_backend == "All" else selected_backend
    df = get_latest_rankings(backend=backend_filter)

    if df.empty:
        st.warning(
            "No rankings in database yet. "
            "Run collector.py at least once (Day 1 stores calibration, "
            "Day 2 generates first predictions)."
        )
        st.stop()

    if show_only_viable:
        df = df[df['label'] == 1]

except Exception as e:
    st.error(f"Could not load rankings: {e}")
    st.stop()

# ── Tab layout ────────────────────────────────────────────────────────────────
tab1, tab2, tab3 = st.tabs(["🏆 Rankings", "📈 Trends", "📊 Backend Comparison"])

# ════════════════════════════════════════════════════════════════════════════
# TAB 1 — Rankings Table
# ════════════════════════════════════════════════════════════════════════════
with tab1:
    st.subheader(f"Top {top_n} Qubits by Viability Score")

    for backend in (BACKENDS if selected_backend == "All" else [selected_backend]):
        sub = df[df['backend'] == backend].nsmallest(top_n, 'viability_rank').copy()
        if sub.empty:
            continue

        color = BACKEND_COLORS[backend]
        st.markdown(f"### {backend}", unsafe_allow_html=False)

        # Colour-code viable vs not
        def highlight_label(row):
            if row['label'] == 1:
                return ['background-color: #e8f5e9'] * len(row)
            return ['background-color: #ffebee'] * len(row)

        display = sub[['viability_rank', 'qubit', 'viability_score',
                        'T1_us', 'T2_us', 'readout_error', 'label']].copy()
        display.columns = ['Rank', 'Qubit', 'Score', 'T1 (μs)', 'T2 (μs)', 'RE', 'Viable']
        display['Viable'] = display['Viable'].map({1: '✅', 0: '❌'})
        display['Score']  = display['Score'].round(4)
        display['T1 (μs)'] = display['T1 (μs)'].round(1)
        display['T2 (μs)'] = display['T2 (μs)'].round(1)
        display['RE']     = display['RE'].round(4)

        st.dataframe(
            display.style.apply(
                lambda row: ['background-color: #e8f5e9' if row['Viable'] == '✅'
                             else 'background-color: #ffebee'] * len(row),
                axis=1
            ),
            use_container_width=True,
            height=min(400, 40 + 35 * len(display))
        )

# ════════════════════════════════════════════════════════════════════════════
# TAB 2 — Trend for a specific qubit
# ════════════════════════════════════════════════════════════════════════════
with tab2:
    st.subheader("Viability Score Trend — Single Qubit")

    col_a, col_b = st.columns(2)
    with col_a:
        trend_backend = st.selectbox("Backend", BACKENDS, key="trend_backend")
    with col_b:
        qubit_options = sorted(df[df['backend'] == trend_backend]['qubit'].unique())
        trend_qubit   = st.selectbox("Qubit", qubit_options, key="trend_qubit")

    try:
        trend_df = get_ranking_history(trend_backend, trend_qubit)

        if trend_df.empty or len(trend_df) < 2:
            st.info("Need at least 2 days of data to show a trend. Check back tomorrow.")
        else:
            fig, axes = plt.subplots(2, 2, figsize=(12, 6))
            fig.suptitle(f"{trend_backend} — Qubit {trend_qubit} History", fontsize=12)

            color = BACKEND_COLORS[trend_backend]
            dates = trend_df['snapshot_date']

            axes[0,0].plot(dates, trend_df['viability_score'], marker='o', color=color, lw=2)
            axes[0,0].set_title('Viability Score')
            axes[0,0].set_ylim(0, 1)

            axes[0,1].plot(dates, trend_df['T1_us'], marker='o', color='#5271C4', lw=2)
            axes[0,1].axhline(100, color='red', ls='--', lw=0.8, alpha=0.6, label='Threshold')
            axes[0,1].set_title('T1 (μs)')
            axes[0,1].legend(fontsize=8)

            axes[1,0].plot(dates, trend_df['T2_us'], marker='o', color='#3BAD6E', lw=2)
            axes[1,0].axhline(50, color='red', ls='--', lw=0.8, alpha=0.6, label='Threshold')
            axes[1,0].set_title('T2 (μs)')
            axes[1,0].legend(fontsize=8)

            axes[1,1].plot(dates, trend_df['readout_error'], marker='o', color='#E07B39', lw=2)
            axes[1,1].axhline(0.05, color='red', ls='--', lw=0.8, alpha=0.6, label='Threshold')
            axes[1,1].set_title('Readout Error')
            axes[1,1].legend(fontsize=8)

            for ax in axes.flat:
                ax.tick_params(axis='x', rotation=30, labelsize=7)
                ax.grid(True, alpha=0.3)

            plt.tight_layout()
            st.pyplot(fig)

    except Exception as e:
        st.error(f"Could not load trend: {e}")

# ════════════════════════════════════════════════════════════════════════════
# TAB 3 — Backend Comparison
# ════════════════════════════════════════════════════════════════════════════
with tab3:
    st.subheader("Backend Comparison — Latest Snapshot")

    try:
        all_df = get_latest_rankings()
        if all_df.empty:
            st.info("No data yet.")
        else:
            summary_rows = []
            for b in BACKENDS:
                sub = all_df[all_df['backend'] == b]
                if sub.empty:
                    continue
                summary_rows.append({
                    'Backend':        b,
                    'Qubits Ranked':  len(sub),
                    'Viable (%)':     f"{100*sub['label'].mean():.1f}%",
                    'Mean Score':     f"{sub['viability_score'].mean():.3f}",
                    'Top Qubit':      int(sub.loc[sub['viability_rank'].idxmin(), 'qubit']),
                    'Top Score':      f"{sub['viability_score'].max():.3f}",
                    'Mean T1 (μs)':   f"{sub['T1_us'].mean():.1f}",
                    'Mean RE':        f"{sub['readout_error'].mean():.4f}",
                })
            st.dataframe(pd.DataFrame(summary_rows).set_index('Backend'),
                         use_container_width=True)

            # Score distribution plot
            fig, ax = plt.subplots(figsize=(10, 4))
            for b in BACKENDS:
                sub = all_df[all_df['backend'] == b]
                if sub.empty: continue
                ax.hist(sub['viability_score'], bins=30, alpha=0.6,
                        color=BACKEND_COLORS[b], label=b.replace('ibm_', ''))
            ax.set_xlabel('Viability Score')
            ax.set_ylabel('Qubit Count')
            ax.set_title('Score Distribution per Backend (Latest Snapshot)')
            ax.legend()
            ax.grid(True, alpha=0.3)
            plt.tight_layout()
            st.pyplot(fig)

    except Exception as e:
        st.error(f"Could not load comparison: {e}")

# ── Footer ────────────────────────────────────────────────────────────────────
st.divider()
st.caption(
    "**Model:** Random Forest | **Training:** Dec 28 2025 – Jan 02 2026 | "
    "**LOBO Mean AUC:** 0.904 | **Jan03 Holdout AUC:** 0.865 | "
    "**Features:** 17 historical (no leakage) | "
    "**Author:** Vattikuti Uday Kiran, LPU"
)
